on:

  pull_request:
    branches:
      - master

  push:
    branches:
      - master

name: "Build & Release"

jobs:

  build:
    name: Build Android and iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Get Flutter version from pubspec
        run: |
          set -e
          _flutterVersion=$( yq -r .environment.flutter pubspec.yaml )
          echo "FLUTTER_VERSION=${_flutterVersion}" >> $GITHUB_ENV
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          architecture: x64
      - name: Generate Android and iOS build
        run: |
          flutter pub get
          flutter build apk
          flutter build appbundle
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            build/app/outputs/flutter-apk/
            build/app/outputs/bundle/release/
            build/ios/iphoneos/app.ipa

  release:
    name: Add tag and create release
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: |
          set -e
          _version= cut -c 1-5 <<< $( yq -r .version pubspec.yaml )
          echo "VERSION=${_version}" >> $GITHUB_ENV
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: builds
          path: |
            build/app/outputs/flutter-apk/
            build/app/outputs/bundle/release/
            build/ios/iphoneos/app.ipa
      - name: Push to Releases
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "**/*.aab,**/*.apk,**/*.ipa"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.ACCESS_TOKEN }}
