on:

  pull_request:
    branches:
      - master

  push:
    branches:
      - master

name: "Build & Release"

jobs:

  build:
    name: Build Android and iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.7.3'
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            build/app/outputs/flutter-apk/
            build/app/outputs/bundle/release/
            build/ios/iphoneos/app.ipa

  release:
    name: Add tag and create release
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: builds
      - name: Push to Releases
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "**/*.aab,**/*.apk,**/*.ipa"
          tag: v1.0.0
          token: ${{ secrets.ACCESS_TOKEN }}
